include $(TOPDIR)/rules.mk

PKG_NAME:=luci-theme-i-love-luci
PKG_VERSION:=1.0.1
PKG_RELEASE:=1

LUCI_TITLE:=I Love LuCI theme login shell
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all
LUCI_URL:=https://github.com/3aa49ec6bfc910647fa1c5a013e48eef/i-love-luci
LUCI_MINIFY_JS:=0
LUCI_MINIFY_CSS:=0

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=3aa49ec6bfc910647fa1c5a013e48eef

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
